name: dgul_ai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.7.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.7+1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  file_picker: ^8.3.2
  mime: ^2.0.0
  speech_to_text: ^6.6.1
  simple_ripple_animation: ^0.1.0
  logger: ^2.6.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/gifs/
