// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZ2HtVKM3DrIPNcvF1Z-CgC7bfVWUjzg',
    appId: '1:188510324480:web:37db3ffacefa5e6a68d5e5',
    messagingSenderId: '188510324480',
    projectId: 'dgul-ai',
    authDomain: 'dgul-ai.firebaseapp.com',
    storageBucket: 'dgul-ai.firebasestorage.app',
    measurementId: 'G-1HH8HHWV5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANbBEyAWgzhGm2LMnIyRM6YSG9FEt2BwM',
    appId: '1:188510324480:android:c30d739b8bce519968d5e5',
    messagingSenderId: '188510324480',
    projectId: 'dgul-ai',
    storageBucket: 'dgul-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHFzQ-JL7aDghT6F8-yaMPPrr-wD9_mRg',
    appId: '1:188510324480:ios:4e1114003531e78768d5e5',
    messagingSenderId: '188510324480',
    projectId: 'dgul-ai',
    storageBucket: 'dgul-ai.firebasestorage.app',
    iosClientId:
        '188510324480-0hak31ai9fea5c12dd7alamdoth196ed.apps.googleusercontent.com',
    iosBundleId: 'com.dgul.maritimeai',
  );
}
